### ISSUE TITLE
(URGENT) Action does not work with custom / private flavors

### ISSUE THREAD

**Issue by ronaldtse** [actions-mn/setup#10]
I'm working on a Metanorma-Ribose document, but the build process dies because of the private flavor.

```
...
Run metanorma site generate --agree-to-terms
  metanorma site generate --agree-to-terms
  shell: /usr/bin/bash -e {0}

[info]: Compiling /home/runner/work/.../report/document.adoc ...
[metanorma] Error: loading gem `metanorma-ribose` failed. Exiting.

Troubleshooting:
1. If you are using metanorma via bundler/ruby, make sure that your
   Gemfile contains a line:
     gem "metanorma-ribose"

2. If you are using brew/choco/snap packages, please report an issue
   to https://github.com/metanorma/packed-mn/issues/new"
Error: Process completed with exit code 1.
```

My Gemfile:
```ruby
source 'https://rubygems.org'

gem "metanorma-cli"
gem "metanorma-ribose"
```

My GHA workflow:
```yaml
name: generate

on:
  push:
    branches: [ main ]
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  pull_request:
  workflow_dispatch:

concurrency:
  group: '${{ github.workflow }}-${{ github.job }}-${{ github.head_ref || github.ref_name }}'
  cancel-in-progress: true

jobs:
  build:
    name: Compile Metanorma site
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ github.token }}
        submodules: true

    - uses: actions/cache@v3
      with:
        path: ~/.fontist
        key: fontist-ubuntu-latest
        restore-keys: fontist-ubuntu-latest

    - uses: actions-mn/setup@master

    - run: metanorma site generate --agree-to-terms

    - uses: actions/upload-artifact@v3
      if: startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/main'
      with:
        name: site
        path: site

  release:
    name: Release package
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: site

    - name: Display structure of downloaded files
      run: ls -R

    - name: Compress files
      run: zip -9 -r package.zip ./*

    - name: Upload release
      id: upload-release-asset
      uses: softprops/action-gh-release@v1
      with:
        body: Automatic release of ${{ github.ref }}
        files: |
          package.zip
```

**Comment by CAMOBAP** [comment]
This action is based on `packed-mn` which doesn't allow install additional flavors. I suggest to:
 - move to a private container
 - use a regular container and install `metanorma-ribose` with https://github.com/metanorma/ci/blob/main/gemfile-to-bundle-add.sh
 - install everything with ruby

**Comment by ronaldtse** [comment]
Thank you @CAMOBAP is the easiest way to use a regular container? Do we have an action-mn action for using the docker container?

**Comment by CAMOBAP** [comment]
@ronaldtse there impossible to implement setup action for containers because containers are specified per job. I think we need something really close to https://github.com/metanorma/ci/blob/main/.github/workflows/sample-docker.yml

i.e.

```
....
jobs:
  test-docker:
    runs-on: ubuntu-latest
    container:
      image: metanorma
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: actions/cache@v2
        with:
          path: /config/fonts
          key: fontist-docker
          restore-keys: fontist-docker

      - run: apt-get update -y && apt-get install -y gcc g++ ruby-dev

      - uses: metanorma/ci/docker-gem-install@main

      - uses: actions-mn/cli/site-gen@main
        with:
          agree-to-terms: true

      - uses: actions/upload-artifact@v2
        with:
          name: site
          path: site
```
